name: CI
on:
  push:
    branches:
      - master
jobs:
  validate-and-test:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        run: bundle exec fastlane test
